//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public long ID { get; set; }
        public string Content { get; set; }
        public Nullable<long> QuesionID { get; set; }
        public string Image { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
