//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiLam
    {
        public int MaLopKiemTra { get; set; }
        public Nullable<double> TongDiem { get; set; }
        public long MaHocVien { get; set; }
        public Nullable<System.DateTime> NgayKiemTra { get; set; }
    
        public virtual HocVien HocVien { get; set; }
        public virtual LopKiemTra LopKiemTra { get; set; }
    }
}
