//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauHoi()
        {
            this.DeThis = new HashSet<DeThi>();
        }
    
        public long MaCauHoi { get; set; }
        public string BieuThuc { get; set; }
        public string NoiDung { get; set; }
        public string BieuThucB { get; set; }
        public string BieuThucD { get; set; }
        public string BieuThucC { get; set; }
        public string BieuThucA { get; set; }
        public string CauA { get; set; }
        public string CauB { get; set; }
        public string CauC { get; set; }
        public string CauD { get; set; }
        public string CauE { get; set; }
        public Nullable<int> DapAn { get; set; }
        public Nullable<int> DoKho { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public int MaMonHoc { get; set; }
        public long MaGiangVien { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<long> ChuongID { get; set; }
    
        public virtual Chuong Chuong { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeThi> DeThis { get; set; }
    }
}
