//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning_V2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELearningDB : DbContext
    {
        public ELearningDB()
            : base("name=ELearningDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiGiang> BaiGiangs { get; set; }
        public virtual DbSet<BaiLam> BaiLams { get; set; }
        public virtual DbSet<CauHoi> CauHois { get; set; }
        public virtual DbSet<Chuong> Chuongs { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<DeThi> DeThis { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<HocVien> HocViens { get; set; }
        public virtual DbSet<KeyAPI> KeyAPIs { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<LopKiemTra> LopKiemTras { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<Reply> Replies { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<TrangThaiHeThong> TrangThaiHeThongs { get; set; }
    }
}
