//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Content { get; set; }
        public Nullable<long> CourseID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
