//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public long ID { get; set; }
        public string HoVaTen { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
        public Nullable<double> SoDu { get; set; }
        public string MaXacNhan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
