//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public long ID { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public long CreateBy { get; set; }
        public long CommentID { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
