//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public long ID { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public long CreatedBy { get; set; }
        public int LopID { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
